# Generated by Django 3.1.4 on 2021-01-05 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210102_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(default='+91-', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='+91-', max_length=15),
        ),
    ]
