# Generated by Django 3.1.4 on 2021-01-15 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210105_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_id', models.CharField(default='', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=18)),
                ('phone', models.CharField(default='+91-', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=15)),
                ('address', models.TextField(default='', max_length=1000)),
                ('college', models.CharField(default='', max_length=1000)),
                ('department', models.CharField(default='', max_length=200)),
                ('profile_link', models.CharField(max_length=500)),
                ('image', models.ImageField(default='default_user.png', upload_to='media/student_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
