# Generated by Django 3.1.4 on 2021-01-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(default='', max_length=10000)),
                ('outcomes', models.TextField(default='', max_length=10000)),
                ('structure', models.TextField(default='', max_length=10000)),
                ('prerequisites', models.TextField(default='', max_length=10000)),
                ('credits', models.IntegerField(default=3)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.IntegerField(default=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_running', models.BooleanField(default=False)),
                ('is_offered', models.BooleanField(default=False)),
                ('banner_image1', models.ImageField(default='default_course.png', upload_to='media/course_images')),
                ('banner_image2', models.ImageField(default='default_course.png', upload_to='media/course_images')),
                ('desc_file1', models.FileField(upload_to='media/course_files')),
                ('desc_file2', models.FileField(upload_to='media/course_files')),
                ('students_file', models.FileField(upload_to='media/course_files/students')),
                ('instructor1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor1', to='accounts.instructor')),
                ('instructor2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor2', to='accounts.instructor')),
            ],
        ),
    ]
