# Generated by Django 3.1.4 on 2021-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210102_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='enrolledstudent',
            name='is_fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='current_batch',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
