# Generated by Django 3.1.4 on 2021-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210105_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc_file1',
            field=models.FileField(blank=True, null=True, upload_to='media/course_files'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc_file2',
            field=models.FileField(blank=True, null=True, upload_to='media/course_files'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_file',
            field=models.FileField(blank=True, null=True, upload_to='media/course_files/students'),
        ),
    ]
