# Generated by Django 3.1.4 on 2021-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210106_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sub_areas',
            field=models.CharField(default='', max_length=200, verbose_name='Sub Areas'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='', max_length=200, verbose_name='Subject Areas'),
        ),
        migrations.AlterField(
            model_name='enrolledstudent',
            name='status',
            field=models.CharField(choices=[('T', 'Pursuing'), ('P', 'Passed'), ('F', 'Failed'), ('W', 'Withdrawn'), ('D', 'Deregistered')], default='Pursuing', max_length=15),
        ),
    ]
