# Generated by Django 3.1.4 on 2021-01-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teachingassistant'),
        ('courses', '0007_auto_20210114_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teaching_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ta', to='accounts.teachingassistant'),
        ),
    ]
